### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by guilhermeteodoro** [SauloSilva/sinatra-active-model-serializers#13]
@SauloSilva I think we're missing the following dependencies on gemspec:

```rb
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-active-record'
```

**Comment by SauloSilva** [comment]
@guilhermeteodoro yes, I agree. You could contribute with PR?

**Comment by SauloSilva** [comment]
@guilhermeteodoro thanks man.
