### ISSUE TITLE
Specifying Serializer

### ISSUE THREAD

**Issue by jamesformica** [SauloSilva/sinatra-active-model-serializers#4]
There seems to be an issue with specifying the serializer in a route. I have tried to following syntax with no success

        section = Section.first
        json(section, {serializer: DumSerializer})

The serializer chosen will always be the default serializer which in this case is Section_Serializer.rb

I have tried to follow the syntax specified at https://github.com/rails-api/active_model_serializers#specify-a-serializer

Thanks

**Comment by SauloSilva** [comment]
@jamesformica this gem does not support this feature at the moment but is a nice feature to be implemented.
Would you like to open a PR adding this feature? It would be very much appreciated.

Thanks man :smile:

**Comment by SauloSilva** [comment]
@jamesformica I checked and I found solution for the case. For working with specify serializer  I changed this [line on json method](https://github.com/SauloSilva/sinatra-active-model-serializers/blob/master/lib/sinatra-active-model-serializers/json.rb#L13) to:

```ruby
serializer = options.fetch(:serializer, ActiveModel::Serializer.serializer_for(object, options))
```

**Comment by adrianotadao** [comment]
This is has been resolved here: https://github.com/SauloSilva/sinatra-active-model-serializers/pull/10

**Comment by adrianotadao** [comment]
@jamesformica Now, you can use: `{ serializer: DumSerializer }` :+1:

**Comment by SauloSilva** [comment]
@adrianotadao and @jamesformica, good job 


Thanks man :smile:
