### ISSUE TITLE
Each Serializer

### ISSUE THREAD

**Issue by SauloSilva** [SauloSilva/sinatra-active-model-serializers#5]
These [features](https://github.com/rails-api/active_model_serializers#2-for-an-array-resource) should be implemented here.

**Comment by tegon** [comment]
:+1:

**Comment by roinacio** [comment]
+1

**Comment by WagnerMoreira** [comment]
+1 :sunglasses: #200!

**Comment by KarllosSouza** [comment]
+1

**Comment by guilhermeteodoro** [comment]
+1 !!

**Comment by AndersonFurlane** [comment]
+1 :eyes:

**Comment by nayarac** [comment]
+1 !!

**Comment by SauloSilva** [comment]
@tegon @AndersonFurlane @roinacio @guilhermeteodoro @WagnerMoreira @nayarac @KarllosSouza  [done](https://rubygems.org/gems/sinatra-active-model-serializers/versions/0.2.0)

**Comment by adrianotadao** [comment]
@SauloSilva Better late than never :joy:

**Comment by SauloSilva** [comment]
@adrianotadao yep :smile:

**Comment by roinacio** [comment]
Lindo! @SauloSilva =*

**Comment by AndersonFurlane** [comment]
GGWP @SauloSilva
